#!/bin/bash

[ -d /var/lib/cicd]
if [ $? -ne 0 ]
 then mkdir /var/lib/cicd
fi

cd /tmp
git clone git@github.com:thedinamo/lab-CI-CD.git
git log > /var/lib/cicd/tmplog
cd /var/lib/cicd
if diff tmplog originlog > /dev/null
 then rm -rf /var/lib/cicd ; exit
fi

ansible-playbook playbook.yml

mv 

